### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by davidfergon** [pacedotdev/community#1]
IMPROVEMENT

Visualize cards as a kanban board Future work --> Up next --> Doing --> Done

**Comment by matryer** [comment]
@davidfergon Thanks for opening this, it was something we considered.

We decided against that design because we find horizontal scroll to be a difficult experience to work with. And those boards tend to end up having both horizontal *and* vertical scroll, so they can get as many cards as possible into one view.

In our experience, have too much information on the screen makes the work feel unachievable; there's simply too much to do.

While having a more limited view doesn't change the amount of work, we found it encourages teams to pay more attention to the most important stuff, a worthwhile exercise.

I hope this explains our rationale. Please let us know your other thoughts.

**Comment by whilp** [comment]
> While having a more limited view doesn't change the amount of work, we found it encourages teams to pay more attention to the most important stuff, a worthwhile exercise.

FWIW, as a kanban nerd, I very much appreciated the experience in pace for this reason! I’ve spent countless hours trying to force other tools (JIRA, Asana, GitHub issues/projects, ...) to focus on what’s in progress. But since most tools present all states in the same view as columns or rows, anything more than a trivial amount of work immediately overwhelms. The sections in pace balance the priorities nicely and should keep me/us focused on what we can get done.

**Comment by dahernan** [comment]
@whilp I'm quite happy you like it, was specially design with that in mind
