### ISSUE TITLE
[build:d8d06d29] 'Related' is just too vague

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#12]
When attaching a related card, there's no context. I dont know if a related issue is a dependency or not, so its basically pointless.

It doesnt need to be complex. Is this an upstream or downstream relationship.... thats all

I'd love to see that graph visually too.

**Comment by matryer** [comment]
@sipickles In an attempt to be minimalist about this, we kept it simple and may have gone too far. We will be showing the reverse relationship, and when we do that it might be an opportunity to redesign this component so that you could potentially add parent and child relationships.

To answer your question, currently you can only add children.

**Comment by matryer** [comment]
@sipickles We've done some work on this today. We have exposed the inverse relationship (children to parents). Please check it out at https://pace.dev/app and let us know if this is clearer.

**Comment by dahernan** [comment]
Closed for now, let us know if you have more comments

**Comment by sipickles** [comment]
@dahernan I took a look but I couldn't seem to create a related parent. Did I miss something?

**Comment by dahernan** [comment]
You can not create a parent card. We just display the parent cards.

For creation is always from parent, create related
