### ISSUE TITLE
[build:f9f95b08] 'Updates on' what?

### ISSUE THREAD

**Issue by kinbiko** [pacedotdev/community#26]
The toggle 'Updates on' sounds awkward, and it's not clear what it means. I'm guessing it means that I get notified if there's a change to this particular card? In which case 'Notify me' would be clearer. Maybe I'm missing it's intended meaning -- I'm testing the app out on my own.

**Comment by matryer** [comment]
@kinbiko Fair comment. We have "Muted" and "Updates on" because we mostly aren't going to be notifying people (e.g. we aren't pinging your phone) so it's more about keeping updated or 'being interested'. In fact, the API calls it "interested users".

But we're open to changing the labels if we can find something that makes it clearer.

**Comment by kinbiko** [comment]
"Updates on" sounds like an incomplete sentence if you don't toggle it on and off again to get the context. "Updates on... every Tuesday?". Maybe "Keep me updated" is clearer?

Side note: Would be cool with a tool tip on hover that explains what it does. Right now I'm the only member of the team, and it's still not clear to me what effect this toggle has.

**Comment by fallion** [comment]
Perhaps `Updates: ON` would be more clear.

**Comment by matryer** [comment]
@fallion We've tweaked this. I wonder if you could take a look at let me know what you think?

**Comment by dahernan** [comment]
Closed for now, let us know if you suggest more adjustments
