### ISSUE TITLE
[build:784fb1e1] View/Change email on account

### ISSUE THREAD

**Issue by sipickles** [pacedotdev/community#33]
I'm not sure if we set up pace with private gmail accounts - I dont see my email listed on the profile page. 

If so, we'd like to switch to our group emails.

**Comment by dahernan** [comment]
on your org -> people you can see everybody email. We could added in your profile, but you are not able to change it, because is verified by the OAuth provider. This has a series of advantages, like if you remove people on your gsuite, or outlook, they will not longer have access to Pace, because OAuth would not let you login with that email anymore.
 
I will suggest that you can invite people by email on people, and remove the users that you not longer used.

**Comment by matryer** [comment]
I like the idea of showing the account email in the profile page.

**Comment by matryer** [comment]
@sipickles I've added the email address to the profile page so you can see which account you used to sign in. 

To access it, (Hard reload for latest version) go to an org, and choose *Your profile* from the user dropdown in the top right.

**Comment by sipickles** [comment]
Thanks for the visibility. 

Your point about gsuite controlling access is a good one, but thats exactly our problem. We set up our pace accounts before our gsuite was active. Now we'd like to switch our pace accounts to use the gsuite addresses. Its not an unusual request to change email addresses on an account :)

**Comment by matryer** [comment]
@sipickles You're right it isn't unreasonable, but it turns out to be pretty difficult on our end because the auth providers give us user IDs that we trust. If you use a different account, it will give us a different user ID. So to Pace, you'd be two different people.

I know it's annoying, but the easiest fix I can think of today would be to invite your new email addresses to the org, and remove your old ones using the *People* manager page. Will that work?

**Comment by owenhaynes** [comment]
Another solution would be link another identity to an account, but then that would mean managing your own user ids.

**Comment by dahernan** [comment]
Yes, @owenhaynes that is the most realistic and long term solution, however is not only managing user ids, you have to have a way to challenge the auth, to prove that you are owner of the account. 

Also more enterprise companies don't usually like that you can authenticate with multiple providers.
For that type of customers, we are thinking about a way that you just manage your users with your provider, and you don't have to invite/remove users from pace, and that has to fit with more relaxed user management for other companies

**Comment by matryer** [comment]
Closing for now.
