### ISSUE TITLE
Issue loading public preview on Safari [build:a2d4247d] 

### ISSUE THREAD

**Issue by dnys1** [pacedotdev/community#38]
I receive the following errors launching https://pace.dev/app/ on Safari 13.1.1 on macOS 10.15.5:

<img width="1792" alt="Screen Shot 2020-07-06 at 3 30 04 PM" src="https://user-images.githubusercontent.com/24740863/86658057-99d70e00-bf9d-11ea-90b7-1226ed7a2416.png">

**Comment by matryer** [comment]
@dnys1 We are sorry that happened. It looks like our new dark mode auto-detection code wasn't guarded enough. It seems that the browsers are all in the process of implementing the various APIs. Safari is one of our supported browsers so we'll do what we can to make sure this doesn't happen again. Please let me know if the fix is working for you. You may need to do a hard reload to ensure you pull the latest version from our servers.
